### ISSUE TITLE
INTEM1.EXE refuses to open the database

### ISSUE THREAD

**Issue by auraes** [Utodev/DRC#26] opened 2021-03-13 12:57 UTC
Hi,
I compile my database under Linux like this:
```
./drf pc vga BLANK_EN.DSF mygame.json
php drb.php pc vga en mygame.json PART1.DDB
```
But I can't use the INTEM1.EXE program under DOSBOX; only INTSM1.EXE works.
INTEM1.EXE: `"The file PART1.DDB is incompatible with this program"`
Am I doing it wrong?

**Comment by Utodev** [comment] 2021-04-03 21:49
Hi, 

Sorry for the long delay in response. It's a bug, which in fact affects all targets, but apparently not all interpreters complain. The problem is the DDB file is being generated with the Spanish language flag on. 

I don't have time right now to fix it, but you can try the following: 

1) using any text editor open file drb.php
2) Locate a line like this:

  if (($language=='ES') || ($language!='PT')) $b = $b | 1;

3) Replace "!=" with  "=="

I believe that should do it, but I don't really have the time right now to check.

I hope it helps.

**Comment by auraes** [comment] 2021-04-04 03:15
The patch works. Thanks.

**Comment by Utodev** [comment] 2021-04-04 17:47
Thank you for your feedback. The patch has been committed to the repository so I'm closing this issue.

**Closed as completed by Utodev** 2021-04-04 17:47 UTC
